# Generated by Django 4.2.20 on 2025-03-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('Select', 'Select'), ('Sales', 'Sales'), ('Services', 'Services'), ('Product_Service', 'Product_Service')], default='Select', max_length=25)),
                ('business_name', models.CharField(blank=True, max_length=20)),
                ('business_reg_no', models.CharField(blank=True, max_length=20)),
                ('business_address', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=20)),
                ('acc_name', models.CharField(blank=True, max_length=20)),
                ('acc_no', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['profile'],
            },
        ),
    ]
