# Generated by Django 4.2.20 on 2025-03-19 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=20)),
                ('bank', models.CharField(blank=True, max_length=20)),
                ('acc_number', models.IntegerField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('base_amount', models.IntegerField(blank=True, help_text='Enter Base Amount')),
                ('charges_percentage', models.IntegerField(blank=True, default=0, help_text='Enter Percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
