# Generated by Django 4.2.20 on 2025-03-19 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSetTransact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_amount', models.IntegerField(help_text='Enter Maximum Amount')),
                ('min_amount', models.IntegerField(help_text='Enter Minimum Amount')),
                ('trans_id', models.CharField(blank=True, max_length=8)),
                ('current_location', models.CharField(max_length=35)),
                ('prefered_method', models.CharField(choices=[('Card Payment', 'Card Payment'), ('Bank Transfer', 'Bank Transfer'), ('transfer_or_card', 'transfer_or_card')], default='Card Payment', max_length=50)),
                ('trans_status', models.BooleanField(blank=True, null=True)),
                ('remote_option', models.BooleanField()),
                ('trans_remark', models.TextField(blank=True, default='enter a remark', max_length=35)),
                ('charges_pay_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('charges_amount_paid', models.IntegerField(blank=True, help_text='Enter Maximum Amount', null=True)),
                ('payment_confirmed', models.BooleanField(blank=True, default=False)),
                ('comp_bank_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.companybankdetail')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberTransact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_amount', models.IntegerField(help_text='Enter Exam score')),
                ('current_location', models.CharField(max_length=45)),
                ('payment_method', models.CharField(choices=[('Card Payment', 'Card Payment'), ('Bank Transfer', 'Bank Transfer'), ('transfer_or_card', 'transfer_or_card')], default='Card Payment', max_length=35)),
                ('delivery_method', models.CharField(choices=[('In-Person', 'In-Person'), ('Remote Delivery', 'Remote Delivery'), ('Third Party', 'Third Party')], default='In-Person', max_length=15)),
                ('trans_status', models.BooleanField()),
                ('trans_remark', models.TextField(default='subscriber remark', max_length=55)),
                ('subscriber', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trans_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_ref', to='transaction.merchantsettransact')),
            ],
            options={
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('trans_success', models.BooleanField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trans_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='transaction.subscribertransact')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCommssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.IntegerField(help_text='Enter Maximum Amount')),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('bank_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.companybankdetail')),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.merchantsettransact')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
